### ISSUE TITLE
[Executor] Graceful shutdown is not implemented

### ISSUE THREAD

**Issue by SayedAlesawy** [SayedAlesawy/Videra-Ingestion#9]
## Description
It seems that the executor doesn't handle graceful shutdown. Also it needs 2 `SIGTERM` to actually terminate. This is causing a process pile up in the container.

## Expected
Executor should intercept `SIGTERM` and/or `SIGKILL` and gracefully terminate, i.e. terminate any sub-processes or threads.

## Actual
Executor doesn't terminate on the first `SIGTERM` which is causing a process pile up in the container. Also it seems that the piled up processes have different `pid` than that of the main process, probably sub-processes.

**Comment by Kareem-Emad** [comment]
https://github.com/SayedAlesawy/Videra-Ingestion/pull/10
